version: '3.7'
services:
  postgres:
    image: postgres:13.2
    environment:
      POSTGRES_USER: quarkus
      POSTGRES_PASSWORD: quarkus
      POSTGRES_DB: quarkus
    ports:
      - "5432:5432"
  mongo:
    image: mongo:4.0.10
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example


